service: google-trends-bot-ar
frameworkVersion: "2"

plugins:
  - serverless-secrets-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: as-east-1

custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}

functions:
  botar:
    handler: handler.botar
    environment:
      CONSUMER_KEY: ${self:custom.secrets.CONSUMER_KEY_AR}
      CONSUMER_SECRET: ${self:custom.secrets.CONSUMER_SECRET_AR}
      ACCESS_TOKEN_KEY: ${self:custom.secrets.ACCESS_TOKEN_KEY_AR}
      ACCESS_TOKEN_SECRET: ${self:custom.secrets.ACCESS_TOKEN_SECRET_AR}
    # events:
    # - schedule: rate(6 hours)
