service: google-trends-bot-us
frameworkVersion: "2"

plugins:
  - serverless-secrets-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}

functions:
  botus:
    handler: handler.botus
    environment:
      CONSUMER_KEY: ${self:custom.secrets.CONSUMER_KEY_US}
      CONSUMER_SECRET: ${self:custom.secrets.CONSUMER_SECRET_US}
      ACCESS_TOKEN_KEY: ${self:custom.secrets.ACCESS_TOKEN_KEY_US}
      ACCESS_TOKEN_SECRET: ${self:custom.secrets.ACCESS_TOKEN_SECRET_US}
    events:
      - schedule: rate(6 hours)
